"""init

Revision ID: af4efbc476e9
Revises: 
Create Date: 2025-06-04 13:33:51.120830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4efbc476e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=35), nullable=False),
    sa.Column('last_name', sa.String(length=35), nullable=True),
    sa.Column('username', sa.String(length=35), nullable=False),
    sa.Column('workload', sa.Float(), server_default='0', nullable=False),
    sa.Column('rating', sa.Float(), server_default='0', nullable=False),
    sa.Column('mark_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_table('tasks',
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='in_process', nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('task_user_association',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id', name='idx_unique_task_user')
    )
    op.create_index(op.f('ix_task_user_association_id'), 'task_user_association', ['id'], unique=False)
    op.create_table('team_executor_association',
    sa.Column('executor_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['users.telegram_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('executor_id', 'team_id', name='idx_unique_team_user')
    )
    op.create_index(op.f('ix_team_executor_association_id'), 'team_executor_association', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_executor_association_id'), table_name='team_executor_association')
    op.drop_table('team_executor_association')
    op.drop_index(op.f('ix_task_user_association_id'), table_name='task_user_association')
    op.drop_table('task_user_association')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
